version: 2

before:
  hooks:
    - npm --prefix=./ui ci
    - npm --prefix=./ui run build

builds:
  - id: openward
    main: ./cmd/main.go
    binary: openward
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - id: openward
    name_template: "openward_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "openward_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch